name: Publish IRAF Community base image to Docker Hub
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish IRAF Community base to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tepickering/iraf-community
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        dockerfile: Dockerfile-community-base
